name: Push libsmb2 to Espressif Component Service

on:
  push:
    branches:
      - master

jobs:
  upload_components:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 # main
      - name: Upload component to component service
        uses: espressif/upload-components-ci-action@b78a19fa5424714997596d3ecffa634aef8ae20b # v1.0.5
        with:
          name: "libsmb2"
          namespace: "sahlberg"
          api_token: ${{ secrets.ESP_IDF_COMPONENT_API_TOKEN }}